@startuml
left to right direction
:Admins:
:Users:
:Visitors:
rectangle BackOffice
rectangle FrontOffice
Admins -down-|> Users
Visitors -down-|> Users
Users -- FrontOffice
Admins -- BackOffice
@enduml
