@startuml
left to right direction
:Admins:
:Users:
:Visitors:
Admins -down-|> Users
Visitors -down-|> Users
package FrontOffice {
    Users -- (See Posts List)
    Users -- (Access Resume)
    Users -- (Navigate through pages)
    Users -- (Authentication pages and functions)
    Users -- (Comment on posts)
    Users -- (See a full post)
    Users -- (Contact the main admin via a form)
    Users -- (Access Social Medias of Main Admin)
}
package BackOffice {
    Admins -- (Manage users rights)
    Admins -- (Check and validate comments)
    Admins -- (Create and edit posts)
}
@enduml
